#installing the tensorflow gup library

In [3]:
!pip install tensorflow-gpu


     |████████████████████████████████| 458.3 MB 11 kB/s 


#install all the packages that will use in the RNN

In [4]:
import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout,Bidirectional
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import regularizers
import tensorflow.keras.utils as ku
import numpy as np
import zipfile

#the dataset you have given to me for traning

In [6]:
lyrics=[]
file=open('/content/lyrics_dataset.txt','r')
lyrics=file.read()
print(lyrics)  

Let the suicide doors up
I threw suicides on the tour bus
I threw suicides on the private jet
You know what that mean, I'm fly to death
I step in Def Jam buildin' like I'm the shit
Tell 'em give me fifty million or I'ma quit
Most rappers' taste level ain't at my waist level
Turn up the bass 'til it's up-in-yo-face level
Don't do no press but I get the most press kit
Plus, yo, my bitch make your bitch look like Precious
Somethin' 'bout Mary, she gone off that molly
Now the whole party is melted like Dalí
Now everybody is movin' they body
Don't sell me apartment, I'll move in the lobby
Niggas is loiterin' just to feel important
You gon' see lawyers and niggas in Jordans

She said, "'Ye, can we get married at the mall?"
I said, "Look, you need to crawl 'fore you ball
Come and meet me in the bathroom stall
And show me why you deserve to have it all."
(Ball so hard) That shit cray, ain't it Jay?
What she order, fish filet?
"Your whip so cold" – this old thing?
Act like you'll ever be around

#seperating the each line in the lyrics and saving it tho coupus2 variable

In [7]:
corpus2=lyrics.lower().split("\n")
corpus2[0:10]

['let the suicide doors up',
 'i threw suicides on the tour bus',
 'i threw suicides on the private jet',
 "you know what that mean, i'm fly to death",
 "i step in def jam buildin' like i'm the shit",
 "tell 'em give me fifty million or i'ma quit",
 "most rappers' taste level ain't at my waist level",
 "turn up the bass 'til it's up-in-yo-face level",
 "don't do no press but i get the most press kit",
 'plus, yo, my bitch make your bitch look like precious']

# I am replacing the stopword with 'space' and wordtoberemove with 'space' 

In [8]:
stopwords=["(",")","/","\\",".",".",":",'"']
wordtoberemoved=['[chours:]']


In [9]:
for loop in range(len(wordtoberemoved)):
  corpus2=[line.replace(wordtoberemoved[loop]," ") for line in corpus2]

In [10]:
print(corpus2)

['let the suicide doors up', 'i threw suicides on the tour bus', 'i threw suicides on the private jet', "you know what that mean, i'm fly to death", "i step in def jam buildin' like i'm the shit", "tell 'em give me fifty million or i'ma quit", "most rappers' taste level ain't at my waist level", "turn up the bass 'til it's up-in-yo-face level", "don't do no press but i get the most press kit", 'plus, yo, my bitch make your bitch look like precious', "somethin' 'bout mary, she gone off that molly", 'now the whole party is melted like dalí', "now everybody is movin' they body", "don't sell me apartment, i'll move in the lobby", "niggas is loiterin' just to feel important", "you gon' see lawyers and niggas in jordans", '', 'she said, "\'ye, can we get married at the mall?"', 'i said, "look, you need to crawl \'fore you ball', 'come and meet me in the bathroom stall', 'and show me why you deserve to have it all."', "(ball so hard) that shit cray, ain't it jay?", 'what she order, fish filet

In [11]:
for loop in range (len(stopwords)):
  print(stopwords[loop])
  corpus2=[line.replace(stopwords[loop]," ")for line in corpus2]

(
)
/
\
.
.
:
"


In [12]:
print(corpus2)

['let the suicide doors up', 'i threw suicides on the tour bus', 'i threw suicides on the private jet', "you know what that mean, i'm fly to death", "i step in def jam buildin' like i'm the shit", "tell 'em give me fifty million or i'ma quit", "most rappers' taste level ain't at my waist level", "turn up the bass 'til it's up-in-yo-face level", "don't do no press but i get the most press kit", 'plus, yo, my bitch make your bitch look like precious', "somethin' 'bout mary, she gone off that molly", 'now the whole party is melted like dalí', "now everybody is movin' they body", "don't sell me apartment, i'll move in the lobby", "niggas is loiterin' just to feel important", "you gon' see lawyers and niggas in jordans", '', "she said,  'ye, can we get married at the mall? ", "i said,  look, you need to crawl 'fore you ball", 'come and meet me in the bathroom stall', 'and show me why you deserve to have it all  ', " ball so hard  that shit cray, ain't it jay?", 'what she order, fish filet?'

In [13]:
corpus2=[elem.strip()for elem in corpus2 if elem.strip()!=" "]

In [14]:
print(corpus2)

['let the suicide doors up', 'i threw suicides on the tour bus', 'i threw suicides on the private jet', "you know what that mean, i'm fly to death", "i step in def jam buildin' like i'm the shit", "tell 'em give me fifty million or i'ma quit", "most rappers' taste level ain't at my waist level", "turn up the bass 'til it's up-in-yo-face level", "don't do no press but i get the most press kit", 'plus, yo, my bitch make your bitch look like precious', "somethin' 'bout mary, she gone off that molly", 'now the whole party is melted like dalí', "now everybody is movin' they body", "don't sell me apartment, i'll move in the lobby", "niggas is loiterin' just to feel important", "you gon' see lawyers and niggas in jordans", '', "she said,  'ye, can we get married at the mall?", "i said,  look, you need to crawl 'fore you ball", 'come and meet me in the bathroom stall', 'and show me why you deserve to have it all', "ball so hard  that shit cray, ain't it jay?", 'what she order, fish filet?', 'y

#I print the total number of lines in the corpus

In [15]:
print("total number of lines:", len(corpus2))

total number of lines: 6555


#tokenizer is use process of spliting the text into small sentence or spliting the apiece into set of chrachter

In [16]:
tokenizer=Tokenizer(oov_token='OOV')
tokenizer.fit_on_texts(corpus2)
total_words=len(tokenizer.word_index)+1

#total  number of word after  the tokenize

In [18]:
print("total number of words",total_words)

total number of words 6260


# change the words into index values beacuse it will easy to get the text form the index value

In [17]:
reversedwordindex= {v: k for k,v in tokenizer.word_index.items()}

#now i am generating ngram text

In [19]:
input_sequences=[]
for line in corpus2:
  token_list=tokenizer.texts_to_sequences([line])[0]
  for i in range(1,len(token_list)):
    n_gram_sequence=token_list[:i+1]
    input_sequences.append(n_gram_sequence)


In [20]:
print('total number of generated sequence',len(input_sequences))

total number of generated sequence 45796


In [21]:
input_sequences[0:4]

[[79, 2], [79, 2, 1131], [79, 2, 1131, 743], [79, 2, 1131, 743, 20]]

In [22]:
max_len_sequence=max([len(x)for x in input_sequences])

In [23]:
print("maximum length of a sequence",max_len_sequence)

maximum length of a sequence 19


#now saveing the sequence which will help me to train the model

In [24]:
input_sequences=np.array(pad_sequences(input_sequences,maxlen=max_len_sequence,padding='pre'))


In [ ]:
print(input_sequences)

[[   0    0    0 ...    0   79    2]
 [   0    0    0 ...   79    2 1131]
 [   0    0    0 ...    2 1131  743]
 ...
 [   0    0    8 ...  847    7   11]
 [   0    0    0 ...    0   26   10]
 [   0    0    0 ...   26   10    4]]


# I am seperating the X varibale and Y variable

In [25]:
xs=input_sequences[:,:-1]
labels=input_sequences[:,-1]


In [26]:
ys=tf.keras.utils.to_categorical(labels,num_classes=total_words)

In [ ]:
embeddingSize = 500
nodeCount = 150


In [ ]:
model = Sequential()
model.add(Embedding(total_words, embeddingSize, input_length=max_len_sequence-1))
model.add(Bidirectional(LSTM(units=nodeCount, return_sequences = True)))
model.add(Bidirectional(LSTM(units=nodeCount, return_sequences = True)))
model.add(LSTM(nodeCount))
model.add(Dense(total_words, activation='relu'))
model.add(Dense(total_words, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 18, 500)           3130000   
_________________________________________________________________
bidirectional_4 (Bidirection (None, 18, 300)           781200    
_________________________________________________________________
bidirectional_5 (Bidirection (None, 18, 300)           541200    
_________________________________________________________________
lstm_8 (LSTM)                (None, 150)               270600    
_________________________________________________________________
dense_4 (Dense)              (None, 6260)              945260    
_________________________________________________________________
dense_5 (Dense)              (None, 6260)              39193860  
Total params: 44,862,120
Trainable params: 44,862,120
Non-trainable params: 0
__________________________________________

In [ ]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 18, 500)           3130000   
_________________________________________________________________
bidirectional (Bidirectional (None, 18, 300)           781200    
_________________________________________________________________
bidirectional_1 (Bidirection (None, 18, 300)           541200    
_________________________________________________________________
lstm_2 (LSTM)                (None, 150)               270600    
_________________________________________________________________
dense (Dense)                (None, 6260)              945260    
_________________________________________________________________
dense_1 (Dense)              (None, 6260)              39193860  
Total params: 44,862,120
Trainable params: 44,862,120
Non-trainable params: 0
____________________________________________

In [ ]:
e=model.layers[0]
weights=e.get_weights()[0]
print(weights.shape)
word_index=tokenizer.word_index

(6260, 500)


In [ ]:
import matplotlib.pyplot as plt
def plot_graph(history,string):
  plt.plt.(history.history)

In [ ]:
def generate_seq(model,tokenizer,enter_text,n_pred):
  in_text,result=enter_text,enter_text
  for i in range(n_pred):
    encoded=tokenizer.texts_to_sequences([in_text])[0]
    encoded=np.array(encoded)
    yhat=np.argmax(model.predict(encoded),axis=-1)
    
    out_word=' '
    for word,index in tokenizer.word_index.items():
      if (index==yhat).any():
        out_word=word
        break
    in_text,result=out_word,result +' '+ out_word
    return result

In [ ]:

print(generate_seq(model,tokenizer,'we loved',105))

we loved the


In [ ]:
next_words =105
seed_text="we loved"


In [ ]:
for _ in range(next_words):
  token_list=tokenizer.texts_to_sequences([seed_text])
  token_list=pad_sequences([token_list],maxlen=max_len_sequence-1,padding='pre')
  #predicted= model.predict_classes(token_list, verbose=0)
  predicted=np.argmax(model.predict(token_list),axis=-1)
  output_word=" "
  for word ,index in tokenizer.word_index.items():
    if index==predicted:
      output_word=word
      break
  seed_text+=" "+ output_word 

ValueError: ignored

# now I have the made the RNN neural network in Which i gave the embedded layer  and then add the LSTM layer layer and finaly i add the dence layer 

In [32]:
model1 = Sequential()
model1.add(Embedding(total_words, 64, input_length = max_len_sequence -1))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dense(total_words, activation='relu'))
model1.add(Dense(total_words, activation = 'softmax'))
model1.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
print(model1.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 18, 64)            400640    
_________________________________________________________________
bidirectional_2 (Bidirection (None, 200)               132000    
_________________________________________________________________
dense_4 (Dense)              (None, 6260)              1258260   
_________________________________________________________________
dense_5 (Dense)              (None, 6260)              39193860  
Total params: 40,984,760
Trainable params: 40,984,760
Non-trainable params: 0
_________________________________________________________________
None


In [33]:
history=model1.fit(xs, ys, epochs = 80, verbose = 1)

Epoch 1/80
 386/1432 [=======>......................] - ETA: 7:10 - loss: 6.8706 - accuracy: 0.0373

KeyboardInterrupt: ignored

In [30]:
import matplotlib.pyplot as plt

plt.plot(model1.history['accuracy'])
plt.xlabel('epoch')
plt.ylabel('accuracy')
plt.show()

TypeError: ignored

In [34]:
seed_text = "Let the suicide doors up"
next_words = 100

for _ in range(next_words):
  token_list = tokenizer.texts_to_sequences([seed_text])[0]
  token_list = pad_sequences([token_list], maxlen = max_len_sequence-1, padding='pre')
  predicted =np.argmax(model1.predict(token_list),axis=-1)
  output_word = ""
  for word, index in tokenizer.word_index.items():
    if index == predicted:
      output_word = word
      break
  seed_text += " " + output_word

print(seed_text)

Let the suicide doors up the the best the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the
